apiVersion: v1
kind: Secret
metadata:
  name: authorization-service-secret
  labels:
    app: authorization-service
type: Opaque
stringData:
  # Cache credentials
  CACHE_PASSWORD: ""
  CACHE_DB: "0"
 
