// Copyright 2025 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/api.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x12\x1cauthorization.service.api.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xbc\x06\x92A\xc0\x04\x12\x8b\x02\n" +
	"\x19Authorization Service API\x12@REST API for managing authorization policies and access controls\"U\n" +
	"\x1fCanonical Authorization Service\x122https://github.com/canonical/authorization-service*P\n" +
	"\bAGPL-3.0\x12Dhttps://github.com/canonical/authorization-service/blob/main/LICENSE2\x031.0*\x01\x022\x10application/json:\x10application/jsonZ\x8b\x01\n" +
	"\x88\x01\n" +
	"\x06OAuth2\x12~\b\x03(\x042*https://auth.canonical.com/oauth/authorize:&https://auth.canonical.com/oauth/tokenB$\n" +
	"\t\n" +
	"\x05email\x12\x00\n" +
	"\n" +
	"\n" +
	"\x06openid\x12\x00\n" +
	"\v\n" +
	"\aprofile\x12\x00r{\n" +
	"4REST API documentation for the Authorization Service\x12Chttps://github.com/canonical/authorization-service/blob/main/API.md\n" +
	" com.authorization.service.api.v1B\bApiProtoP\x01Z7github.com/canonical/authorization-service/api/proto/v1\xa2\x02\x03ASA\xaa\x02\x1cAuthorization.Service.Api.V1\xca\x02\x1cAuthorization\\Service\\Api\\V1\xe2\x02(Authorization\\Service\\Api\\V1\\GPBMetadata\xea\x02\x1fAuthorization::Service::Api::V1b\x06proto3"

var file_v1_api_proto_goTypes = []any{}
var file_v1_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
