// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/authorization.proto

package v1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request attributes.
	Attributes    *AttributeContext `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_v1_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetAttributes() *AttributeContext {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the authorization check.
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Optional response metadata that will be added to the upstream request.
	HeadersToAdd map[string]string `protobuf:"bytes,2,rep,name=headers_to_add,json=headersToAdd,proto3" json:"headers_to_add,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional response metadata that will be added to the downstream response.
	ResponseHeadersToAdd map[string]string `protobuf:"bytes,3,rep,name=response_headers_to_add,json=responseHeadersToAdd,proto3" json:"response_headers_to_add,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional dynamic metadata that will be emitted to the stats sink.
	DynamicMetadata map[string]string `protobuf:"bytes,4,rep,name=dynamic_metadata,json=dynamicMetadata,proto3" json:"dynamic_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_v1_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CheckResponse) GetHeadersToAdd() map[string]string {
	if x != nil {
		return x.HeadersToAdd
	}
	return nil
}

func (x *CheckResponse) GetResponseHeadersToAdd() map[string]string {
	if x != nil {
		return x.ResponseHeadersToAdd
	}
	return nil
}

func (x *CheckResponse) GetDynamicMetadata() map[string]string {
	if x != nil {
		return x.DynamicMetadata
	}
	return nil
}

type AttributeContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source of a network activity, such as starting a TCP connection.
	Source *Peer `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// The destination of a network activity, such as accepting a TCP connection.
	Destination *Peer `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// Represents a network request, such as an HTTP request.
	Request *Request `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	// The context of the request, such as the user identity.
	ContextExtensions *ContextExtensions `protobuf:"bytes,4,opt,name=context_extensions,json=contextExtensions,proto3" json:"context_extensions,omitempty"`
	// Dynamic metadata associated with the request.
	MetadataContext map[string]string `protobuf:"bytes,5,rep,name=metadata_context,json=metadataContext,proto3" json:"metadata_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttributeContext) Reset() {
	*x = AttributeContext{}
	mi := &file_v1_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeContext) ProtoMessage() {}

func (x *AttributeContext) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeContext.ProtoReflect.Descriptor instead.
func (*AttributeContext) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeContext) GetSource() *Peer {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AttributeContext) GetDestination() *Peer {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *AttributeContext) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AttributeContext) GetContextExtensions() *ContextExtensions {
	if x != nil {
		return x.ContextExtensions
	}
	return nil
}

func (x *AttributeContext) GetMetadataContext() map[string]string {
	if x != nil {
		return x.MetadataContext
	}
	return nil
}

type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address of the peer.
	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The canonical service name of the peer.
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// The labels associated with the peer.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The authenticated identity of the peer.
	Principal string `protobuf:"bytes,4,opt,name=principal,proto3" json:"principal,omitempty"`
	// The certificate properties.
	Certificate   map[string]string `protobuf:"bytes,5,rep,name=certificate,proto3" json:"certificate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_v1_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *Peer) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Peer) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Peer) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Peer) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Peer) GetCertificate() map[string]string {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_v1_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp when the request was received.
	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// The HTTP request headers.
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The HTTP request method.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// The HTTP request path.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// The HTTP request host.
	Host string `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	// The HTTP request scheme.
	Scheme string `protobuf:"bytes,6,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// The HTTP request protocol.
	Protocol string `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The HTTP request body.
	Body string `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	// The HTTP request size.
	Size int64 `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	// The HTTP request ID.
	Id            string `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_v1_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Request) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Request) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContextExtensions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Additional context information.
	Extensions    map[string]string `protobuf:"bytes,1,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextExtensions) Reset() {
	*x = ContextExtensions{}
	mi := &file_v1_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextExtensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextExtensions) ProtoMessage() {}

func (x *ContextExtensions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextExtensions.ProtoReflect.Descriptor instead.
func (*ContextExtensions) Descriptor() ([]byte, []int) {
	return file_v1_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *ContextExtensions) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_v1_authorization_proto protoreflect.FileDescriptor

const file_v1_authorization_proto_rawDesc = "" +
	"\n" +
	"\x16v1/authorization.proto\x12\x1cauthorization.service.api.v1\x1a\x17google/rpc/status.proto\"^\n" +
	"\fCheckRequest\x12N\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2..authorization.service.api.v1.AttributeContextR\n" +
	"attributes\"\xd9\x04\n" +
	"\rCheckResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12c\n" +
	"\x0eheaders_to_add\x18\x02 \x03(\v2=.authorization.service.api.v1.CheckResponse.HeadersToAddEntryR\fheadersToAdd\x12|\n" +
	"\x17response_headers_to_add\x18\x03 \x03(\v2E.authorization.service.api.v1.CheckResponse.ResponseHeadersToAddEntryR\x14responseHeadersToAdd\x12k\n" +
	"\x10dynamic_metadata\x18\x04 \x03(\v2@.authorization.service.api.v1.CheckResponse.DynamicMetadataEntryR\x0fdynamicMetadata\x1a?\n" +
	"\x11HeadersToAddEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19ResponseHeadersToAddEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14DynamicMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x03\n" +
	"\x10AttributeContext\x12:\n" +
	"\x06source\x18\x01 \x01(\v2\".authorization.service.api.v1.PeerR\x06source\x12D\n" +
	"\vdestination\x18\x02 \x01(\v2\".authorization.service.api.v1.PeerR\vdestination\x12?\n" +
	"\arequest\x18\x03 \x01(\v2%.authorization.service.api.v1.RequestR\arequest\x12^\n" +
	"\x12context_extensions\x18\x04 \x01(\v2/.authorization.service.api.v1.ContextExtensionsR\x11contextExtensions\x12n\n" +
	"\x10metadata_context\x18\x05 \x03(\v2C.authorization.service.api.v1.AttributeContext.MetadataContextEntryR\x0fmetadataContext\x1aB\n" +
	"\x14MetadataContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x03\n" +
	"\x04Peer\x12?\n" +
	"\aaddress\x18\x01 \x01(\v2%.authorization.service.api.v1.AddressR\aaddress\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12F\n" +
	"\x06labels\x18\x03 \x03(\v2..authorization.service.api.v1.Peer.LabelsEntryR\x06labels\x12\x1c\n" +
	"\tprincipal\x18\x04 \x01(\tR\tprincipal\x12U\n" +
	"\vcertificate\x18\x05 \x03(\v23.authorization.service.api.v1.Peer.CertificateEntryR\vcertificate\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10CertificateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xd3\x02\n" +
	"\aRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12L\n" +
	"\aheaders\x18\x02 \x03(\v22.authorization.service.api.v1.Request.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12\x16\n" +
	"\x06scheme\x18\x06 \x01(\tR\x06scheme\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12\x12\n" +
	"\x04size\x18\t \x01(\x03R\x04size\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x11ContextExtensions\x12_\n" +
	"\n" +
	"extensions\x18\x01 \x03(\v2?.authorization.service.api.v1.ContextExtensions.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012q\n" +
	"\rAuthorization\x12`\n" +
	"\x05Check\x12*.authorization.service.api.v1.CheckRequest\x1a+.authorization.service.api.v1.CheckResponseB\x82\x02\n" +
	" com.authorization.service.api.v1B\x12AuthorizationProtoP\x01Z7github.com/canonical/authorization-service/api/proto/v1\xa2\x02\x03ASA\xaa\x02\x1cAuthorization.Service.Api.V1\xca\x02\x1cAuthorization\\Service\\Api\\V1\xe2\x02(Authorization\\Service\\Api\\V1\\GPBMetadata\xea\x02\x1fAuthorization::Service::Api::V1b\x06proto3"

var (
	file_v1_authorization_proto_rawDescOnce sync.Once
	file_v1_authorization_proto_rawDescData []byte
)

func file_v1_authorization_proto_rawDescGZIP() []byte {
	file_v1_authorization_proto_rawDescOnce.Do(func() {
		file_v1_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_authorization_proto_rawDesc), len(file_v1_authorization_proto_rawDesc)))
	})
	return file_v1_authorization_proto_rawDescData
}

var file_v1_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_authorization_proto_goTypes = []any{
	(*CheckRequest)(nil),      // 0: authorization.service.api.v1.CheckRequest
	(*CheckResponse)(nil),     // 1: authorization.service.api.v1.CheckResponse
	(*AttributeContext)(nil),  // 2: authorization.service.api.v1.AttributeContext
	(*Peer)(nil),              // 3: authorization.service.api.v1.Peer
	(*Address)(nil),           // 4: authorization.service.api.v1.Address
	(*Request)(nil),           // 5: authorization.service.api.v1.Request
	(*ContextExtensions)(nil), // 6: authorization.service.api.v1.ContextExtensions
	nil,                       // 7: authorization.service.api.v1.CheckResponse.HeadersToAddEntry
	nil,                       // 8: authorization.service.api.v1.CheckResponse.ResponseHeadersToAddEntry
	nil,                       // 9: authorization.service.api.v1.CheckResponse.DynamicMetadataEntry
	nil,                       // 10: authorization.service.api.v1.AttributeContext.MetadataContextEntry
	nil,                       // 11: authorization.service.api.v1.Peer.LabelsEntry
	nil,                       // 12: authorization.service.api.v1.Peer.CertificateEntry
	nil,                       // 13: authorization.service.api.v1.Request.HeadersEntry
	nil,                       // 14: authorization.service.api.v1.ContextExtensions.ExtensionsEntry
	(*status.Status)(nil),     // 15: google.rpc.Status
}
var file_v1_authorization_proto_depIdxs = []int32{
	2,  // 0: authorization.service.api.v1.CheckRequest.attributes:type_name -> authorization.service.api.v1.AttributeContext
	15, // 1: authorization.service.api.v1.CheckResponse.status:type_name -> google.rpc.Status
	7,  // 2: authorization.service.api.v1.CheckResponse.headers_to_add:type_name -> authorization.service.api.v1.CheckResponse.HeadersToAddEntry
	8,  // 3: authorization.service.api.v1.CheckResponse.response_headers_to_add:type_name -> authorization.service.api.v1.CheckResponse.ResponseHeadersToAddEntry
	9,  // 4: authorization.service.api.v1.CheckResponse.dynamic_metadata:type_name -> authorization.service.api.v1.CheckResponse.DynamicMetadataEntry
	3,  // 5: authorization.service.api.v1.AttributeContext.source:type_name -> authorization.service.api.v1.Peer
	3,  // 6: authorization.service.api.v1.AttributeContext.destination:type_name -> authorization.service.api.v1.Peer
	5,  // 7: authorization.service.api.v1.AttributeContext.request:type_name -> authorization.service.api.v1.Request
	6,  // 8: authorization.service.api.v1.AttributeContext.context_extensions:type_name -> authorization.service.api.v1.ContextExtensions
	10, // 9: authorization.service.api.v1.AttributeContext.metadata_context:type_name -> authorization.service.api.v1.AttributeContext.MetadataContextEntry
	4,  // 10: authorization.service.api.v1.Peer.address:type_name -> authorization.service.api.v1.Address
	11, // 11: authorization.service.api.v1.Peer.labels:type_name -> authorization.service.api.v1.Peer.LabelsEntry
	12, // 12: authorization.service.api.v1.Peer.certificate:type_name -> authorization.service.api.v1.Peer.CertificateEntry
	13, // 13: authorization.service.api.v1.Request.headers:type_name -> authorization.service.api.v1.Request.HeadersEntry
	14, // 14: authorization.service.api.v1.ContextExtensions.extensions:type_name -> authorization.service.api.v1.ContextExtensions.ExtensionsEntry
	0,  // 15: authorization.service.api.v1.Authorization.Check:input_type -> authorization.service.api.v1.CheckRequest
	1,  // 16: authorization.service.api.v1.Authorization.Check:output_type -> authorization.service.api.v1.CheckResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_authorization_proto_init() }
func file_v1_authorization_proto_init() {
	if File_v1_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_authorization_proto_rawDesc), len(file_v1_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_authorization_proto_goTypes,
		DependencyIndexes: file_v1_authorization_proto_depIdxs,
		MessageInfos:      file_v1_authorization_proto_msgTypes,
	}.Build()
	File_v1_authorization_proto = out.File
	file_v1_authorization_proto_goTypes = nil
	file_v1_authorization_proto_depIdxs = nil
}
