// Copyright 2025 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Published by other services to the tuple ingestion topic.
type WriteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SequenceId   uint32                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	UserType     string                 `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	UserId       string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceType string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId   string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Organization string                 `protobuf:"bytes,6,opt,name=organization,proto3" json:"organization,omitempty"`
	// Types that are valid to be assigned to Permission:
	//
	//	*WriteRequest_Entitlement
	//	*WriteRequest_Role
	Permission    isWriteRequest_Permission `protobuf_oneof:"permission"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetSequenceId() uint32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *WriteRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *WriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WriteRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *WriteRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *WriteRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *WriteRequest) GetPermission() isWriteRequest_Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *WriteRequest) GetEntitlement() string {
	if x != nil {
		if x, ok := x.Permission.(*WriteRequest_Entitlement); ok {
			return x.Entitlement
		}
	}
	return ""
}

func (x *WriteRequest) GetRole() string {
	if x != nil {
		if x, ok := x.Permission.(*WriteRequest_Role); ok {
			return x.Role
		}
	}
	return ""
}

type isWriteRequest_Permission interface {
	isWriteRequest_Permission()
}

type WriteRequest_Entitlement struct {
	Entitlement string `protobuf:"bytes,7,opt,name=entitlement,proto3,oneof"`
}

type WriteRequest_Role struct {
	Role string `protobuf:"bytes,8,opt,name=role,proto3,oneof"`
}

func (*WriteRequest_Entitlement) isWriteRequest_Permission() {}

func (*WriteRequest_Role) isWriteRequest_Permission() {}

// Published by this service to the error topic when ingestion fails.
type WriteRequestError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    uint32                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TupleSnapshot string                 `protobuf:"bytes,4,opt,name=tuple_snapshot,json=tupleSnapshot,proto3" json:"tuple_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequestError) Reset() {
	*x = WriteRequestError{}
	mi := &file_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequestError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequestError) ProtoMessage() {}

func (x *WriteRequestError) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequestError.ProtoReflect.Descriptor instead.
func (*WriteRequestError) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequestError) GetSequenceId() uint32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *WriteRequestError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *WriteRequestError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WriteRequestError) GetTupleSnapshot() string {
	if x != nil {
		return x.TupleSnapshot
	}
	return ""
}

var File_v1_messages_proto protoreflect.FileDescriptor

const file_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x11v1/messages.proto\x12\x1cauthorization.service.api.v1\"\x97\x02\n" +
	"\fWriteRequest\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\rR\n" +
	"sequenceId\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\tR\buserType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12\"\n" +
	"\forganization\x18\x06 \x01(\tR\forganization\x12\"\n" +
	"\ventitlement\x18\a \x01(\tH\x00R\ventitlement\x12\x14\n" +
	"\x04role\x18\b \x01(\tH\x00R\x04roleB\f\n" +
	"\n" +
	"permission\"\x9f\x01\n" +
	"\x11WriteRequestError\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\rR\n" +
	"sequenceId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0etuple_snapshot\x18\x04 \x01(\tR\rtupleSnapshotB\xfd\x01\n" +
	" com.authorization.service.api.v1B\rMessagesProtoP\x01Z7github.com/canonical/authorization-service/api/proto/v1\xa2\x02\x03ASA\xaa\x02\x1cAuthorization.Service.Api.V1\xca\x02\x1cAuthorization\\Service\\Api\\V1\xe2\x02(Authorization\\Service\\Api\\V1\\GPBMetadata\xea\x02\x1fAuthorization::Service::Api::V1b\x06proto3"

var (
	file_v1_messages_proto_rawDescOnce sync.Once
	file_v1_messages_proto_rawDescData []byte
)

func file_v1_messages_proto_rawDescGZIP() []byte {
	file_v1_messages_proto_rawDescOnce.Do(func() {
		file_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_messages_proto_rawDesc), len(file_v1_messages_proto_rawDesc)))
	})
	return file_v1_messages_proto_rawDescData
}

var file_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_messages_proto_goTypes = []any{
	(*WriteRequest)(nil),      // 0: authorization.service.api.v1.WriteRequest
	(*WriteRequestError)(nil), // 1: authorization.service.api.v1.WriteRequestError
}
var file_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_messages_proto_init() }
func file_v1_messages_proto_init() {
	if File_v1_messages_proto != nil {
		return
	}
	file_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*WriteRequest_Entitlement)(nil),
		(*WriteRequest_Role)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_messages_proto_rawDesc), len(file_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_messages_proto_goTypes,
		DependencyIndexes: file_v1_messages_proto_depIdxs,
		MessageInfos:      file_v1_messages_proto_msgTypes,
	}.Build()
	File_v1_messages_proto = out.File
	file_v1_messages_proto_goTypes = nil
	file_v1_messages_proto_depIdxs = nil
}
