// Copyright 2026 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/permissions.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Permissions   *structpb.Struct       `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPermissionsRequest) Reset() {
	*x = RegisterPermissionsRequest{}
	mi := &file_v1_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPermissionsRequest) ProtoMessage() {}

func (x *RegisterPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPermissionsRequest.ProtoReflect.Descriptor instead.
func (*RegisterPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPermissionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterPermissionsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterPermissionsRequest) GetPermissions() *structpb.Struct {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RegisterPermissionsRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPermissionsResponse) Reset() {
	*x = RegisterPermissionsResponse{}
	mi := &file_v1_permissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPermissionsResponse) ProtoMessage() {}

func (x *RegisterPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPermissionsResponse.ProtoReflect.Descriptor instead.
func (*RegisterPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPermissionsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterPermissionsResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_v1_permissions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{2}
}

func (x *GetPermissionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetPermissionsRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Permissions   *structpb.Struct       `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsResponse) Reset() {
	*x = GetPermissionsResponse{}
	mi := &file_v1_permissions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsResponse) ProtoMessage() {}

func (x *GetPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionsResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetPermissionsResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetPermissionsResponse) GetPermissions() *structpb.Struct {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetPermissionsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetPermissionsResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_v1_permissions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{4}
}

func (x *ListPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermissionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Permissions   []*GetPermissionsResponse `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	NextPageToken string                    `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_v1_permissions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{5}
}

func (x *ListPermissionsResponse) GetPermissions() []*GetPermissionsResponse {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeletePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionsRequest) Reset() {
	*x = DeletePermissionsRequest{}
	mi := &file_v1_permissions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionsRequest) ProtoMessage() {}

func (x *DeletePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionsRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePermissionsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeletePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionsResponse) Reset() {
	*x = DeletePermissionsResponse{}
	mi := &file_v1_permissions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionsResponse) ProtoMessage() {}

func (x *DeletePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_permissions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionsResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_permissions_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_permissions_proto protoreflect.FileDescriptor

const file_v1_permissions_proto_rawDesc = "" +
	"\n" +
	"\x14v1/permissions.proto\x12\x1cauthorization.service.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\x1aRegisterPermissionsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x129\n" +
	"\vpermissions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vpermissions\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"n\n" +
	"\x1bRegisterPermissionsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\rregistered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"P\n" +
	"\x15GetPermissionsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf0\x01\n" +
	"\x16GetPermissionsResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x129\n" +
	"\vpermissions\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vpermissions\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"T\n" +
	"\x16ListPermissionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x99\x01\n" +
	"\x17ListPermissionsResponse\x12V\n" +
	"\vpermissions\x18\x01 \x03(\v24.authorization.service.api.v1.GetPermissionsResponseR\vpermissions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"9\n" +
	"\x18DeletePermissionsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"5\n" +
	"\x19DeletePermissionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa8\x05\n" +
	"\x12PermissionsService\x12\xa6\x01\n" +
	"\x13RegisterPermissions\x128.authorization.service.api.v1.RegisterPermissionsRequest\x1a9.authorization.service.api.v1.RegisterPermissionsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/permissions\x12\xa1\x01\n" +
	"\x0eGetPermissions\x123.authorization.service.api.v1.GetPermissionsRequest\x1a4.authorization.service.api.v1.GetPermissionsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/permissions/{service_id}\x12\x97\x01\n" +
	"\x0fListPermissions\x124.authorization.service.api.v1.ListPermissionsRequest\x1a5.authorization.service.api.v1.ListPermissionsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/permissions\x12\xaa\x01\n" +
	"\x11DeletePermissions\x126.authorization.service.api.v1.DeletePermissionsRequest\x1a7.authorization.service.api.v1.DeletePermissionsResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/permissions/{service_id}B\x80\x02\n" +
	" com.authorization.service.api.v1B\x10PermissionsProtoP\x01Z7github.com/canonical/authorization-service/api/proto/v1\xa2\x02\x03ASA\xaa\x02\x1cAuthorization.Service.Api.V1\xca\x02\x1cAuthorization\\Service\\Api\\V1\xe2\x02(Authorization\\Service\\Api\\V1\\GPBMetadata\xea\x02\x1fAuthorization::Service::Api::V1b\x06proto3"

var (
	file_v1_permissions_proto_rawDescOnce sync.Once
	file_v1_permissions_proto_rawDescData []byte
)

func file_v1_permissions_proto_rawDescGZIP() []byte {
	file_v1_permissions_proto_rawDescOnce.Do(func() {
		file_v1_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_permissions_proto_rawDesc), len(file_v1_permissions_proto_rawDesc)))
	})
	return file_v1_permissions_proto_rawDescData
}

var file_v1_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_permissions_proto_goTypes = []any{
	(*RegisterPermissionsRequest)(nil),  // 0: authorization.service.api.v1.RegisterPermissionsRequest
	(*RegisterPermissionsResponse)(nil), // 1: authorization.service.api.v1.RegisterPermissionsResponse
	(*GetPermissionsRequest)(nil),       // 2: authorization.service.api.v1.GetPermissionsRequest
	(*GetPermissionsResponse)(nil),      // 3: authorization.service.api.v1.GetPermissionsResponse
	(*ListPermissionsRequest)(nil),      // 4: authorization.service.api.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),     // 5: authorization.service.api.v1.ListPermissionsResponse
	(*DeletePermissionsRequest)(nil),    // 6: authorization.service.api.v1.DeletePermissionsRequest
	(*DeletePermissionsResponse)(nil),   // 7: authorization.service.api.v1.DeletePermissionsResponse
	(*structpb.Struct)(nil),             // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_v1_permissions_proto_depIdxs = []int32{
	8, // 0: authorization.service.api.v1.RegisterPermissionsRequest.permissions:type_name -> google.protobuf.Struct
	9, // 1: authorization.service.api.v1.RegisterPermissionsResponse.registered_at:type_name -> google.protobuf.Timestamp
	8, // 2: authorization.service.api.v1.GetPermissionsResponse.permissions:type_name -> google.protobuf.Struct
	9, // 3: authorization.service.api.v1.GetPermissionsResponse.registered_at:type_name -> google.protobuf.Timestamp
	3, // 4: authorization.service.api.v1.ListPermissionsResponse.permissions:type_name -> authorization.service.api.v1.GetPermissionsResponse
	0, // 5: authorization.service.api.v1.PermissionsService.RegisterPermissions:input_type -> authorization.service.api.v1.RegisterPermissionsRequest
	2, // 6: authorization.service.api.v1.PermissionsService.GetPermissions:input_type -> authorization.service.api.v1.GetPermissionsRequest
	4, // 7: authorization.service.api.v1.PermissionsService.ListPermissions:input_type -> authorization.service.api.v1.ListPermissionsRequest
	6, // 8: authorization.service.api.v1.PermissionsService.DeletePermissions:input_type -> authorization.service.api.v1.DeletePermissionsRequest
	1, // 9: authorization.service.api.v1.PermissionsService.RegisterPermissions:output_type -> authorization.service.api.v1.RegisterPermissionsResponse
	3, // 10: authorization.service.api.v1.PermissionsService.GetPermissions:output_type -> authorization.service.api.v1.GetPermissionsResponse
	5, // 11: authorization.service.api.v1.PermissionsService.ListPermissions:output_type -> authorization.service.api.v1.ListPermissionsResponse
	7, // 12: authorization.service.api.v1.PermissionsService.DeletePermissions:output_type -> authorization.service.api.v1.DeletePermissionsResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_permissions_proto_init() }
func file_v1_permissions_proto_init() {
	if File_v1_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_permissions_proto_rawDesc), len(file_v1_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_permissions_proto_goTypes,
		DependencyIndexes: file_v1_permissions_proto_depIdxs,
		MessageInfos:      file_v1_permissions_proto_msgTypes,
	}.Build()
	File_v1_permissions_proto = out.File
	file_v1_permissions_proto_goTypes = nil
	file_v1_permissions_proto_depIdxs = nil
}
