CREATE DATABASE cerberus;
CREATE DATABASE sts;
GRANT ALL PRIVILEGES ON DATABASE cerberus TO cerberus;
GRANT ALL PRIVILEGES ON DATABASE sts TO cerberus;

ALTER DATABASE cerberus OWNER TO cerberus;
ALTER DATABASE sts OWNER TO cerberus;
