apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: echoserver-ztunnel-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: echoserver
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/authorization-service-gateway-istio
        - cluster.local/ns/default/sa/waypoint
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: echoserver-ext-authz
  namespace: default
spec:
  # Target the waypoint gateway for L7 policy enforcement
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: authorization-service-gateway
  # Default action is to require external authorization
  action: CUSTOM
  provider:
    name: "authorization-service"
  
  rules:
  - to:
    - operation:
        paths: ["/echo", "/echo/*"]
        notPaths: ["/echo/health"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: echoserver-allow-health
  namespace: default
spec:
  # Target the whole chain up to the echoserver or the request will be denied after the gateway
  # Client -> Gateway -> Waypoint Proxy -> Ztunnel -> Pod
  # Ztunnel needs to know about allowing the request to the echoserver
  selector:
    matchLabels:
      app: echoserver
  # Allow unauthenticated access to /health
  action: ALLOW
  rules:
  - to:
    - operation:
        paths: ["/health", "/echo/health"]
        methods: ["GET"]
