apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - authorizationpolicy.yaml
  - httproute.yaml

commonLabels:
  example: echoserver-with-authz

images:
  - name: gcr.io/google_containers/echoserver
    newTag: "1.10"
