meshConfig:
  extensionProviders:
    # Define the External Authorizer
    - name: "cerberos"
      envoyExtAuthzGrpc:
        service: "authorization-service.default.svc.cluster.local" # DNS of your authz service
        port: "9090"
        #includeRequestBodyInCheck:
        #  packAsBytes: true
        # optional: 
        # failOpen: false
        # authorizationRequest:
        #   allowedHeaders:
        #     - exact: "cookie"
        # authorizationResponse:
        #   allowedUpstreamHeaders:
        #     - exact: "authorization"  
profile: ambient