name: Validate Route Rules

on:
  pull_request:
    paths:
      - 'authz/model/services/*/rules.yaml'

jobs:
  validate:
    name: Dry-run Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: '1.26'

      - name: Run Rules Dry-Run Validation
        env:
          SERVER_DEVELOPMENT: "true"
          OPEN_FGA_STORE_ID: "dummy"
          OPEN_FGA_AUTHORIZATION_MODEL_ID: "dummy"
          OPEN_FGA_API_KEY: "dummy"
        run: go run main.go seed --dry-run
